# -*- encoding: utf-8 -*-
##############################################################################
#
#    OpenERP, Open Source Management Solution    
#    Copyright (C) 2004-2009 Tiny SPRL (<http://tiny.be>). All Rights Reserved
#    OML : Openerp Mexican Localization
#    Copyleft (Cl) 2008-2021 Vauxoo, C.A. (<http://vauxoo.com>)
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################
{   "name" : "OpenERP Mexican Localization",
    "version" : "",
    "depends" : [
                #Start list of all oficial modules
                #Commented duplicate modules
                #~ "account",
                "account_accountant",
                "account_analytic_analysis",
                "account_analytic_default",
                #"account_analytic_plans",#Error to fix
                "account_anglo_saxon",
                "account_asset",
                #"account_bank_statement_extensions",#Error in test
                "account_budget",
                "account_cancel",
                "account_chart",
                "account_check_writing",
                "account_followup",
                "account_payment",
                "account_report_company",
                "account_sequence",
                "account_test",
                "account_voucher",
                #~ "analytic",
                "analytic_contract_hr_expense",
                "analytic_user_function",
                "anonymization",
                "association",
                "audittrail",
                "auth_crypt",
                #"auth_ldap",#No test
                "auth_oauth",
                "auth_oauth_signup",
                "auth_openid",
                "auth_signup",
                "base_action_rule",
                "base_calendar",
                "base_gengo",
                "base_iban",
                "base_import",
                "base_report_designer",
                "base_setup",
                "base_status",
                "base_vat",
                "board",
                "claim_from_delivery",
                "contacts",
                #~ "crm",
                "crm_claim",
                "crm_helpdesk",
                "crm_partner_assign",
                "crm_profiling",
                "crm_todo",
                "decimal_precision",
                "delivery",
                "document",
                #"document_ftp",#No test
                "document_page",
                "document_webdav",
                "edi",
                "email_template",
                #~ "event",
                "event_moodle",
                "event_sale",
                #~ "fetchmail",
                "fleet",
                "google_base_account",
                "google_docs",
                #~ "hr",
                "hr_attendance",
                "hr_contract",
                "hr_evaluation",
                "hr_expense",
                "hr_holidays",
                "hr_payroll",
                "hr_payroll_account",
                "hr_recruitment",
                "hr_timesheet",
                "hr_timesheet_invoice",
                "hr_timesheet_sheet",
                "idea",
                #~ "knowledge",
                "l10n_ar",
                "l10n_at",
                "l10n_be",
                "l10n_be_coda",
                "l10n_be_hr_payroll",
                "l10n_be_hr_payroll_account",
                "l10n_be_invoice_bba",
                "l10n_bo",
                "l10n_br",
                "l10n_ca",
                "l10n_ch",
                "l10n_cl",
                "l10n_cn",
                "l10n_co",
                "l10n_cr",
                "l10n_de",
                "l10n_ec",
                "l10n_es",
                "l10n_et",
                "l10n_fr",
                "l10n_fr_hr_payroll",
                "l10n_fr_rib",
                "l10n_gr",
                "l10n_gt",
                "l10n_hn",
                "l10n_hr",
                "l10n_in",
                "l10n_it",
                "l10n_lu",
                "l10n_ma",
                "l10n_multilang",
                "l10n_mx",
                "l10n_nl",
                "l10n_pa",
                "l10n_pe",
                "l10n_pl",
                "l10n_pt",
                "l10n_ro",
                "l10n_si",
                "l10n_syscohada",
                "l10n_th",
                "l10n_tr",
                "l10n_uk",
                "l10n_us",
                "l10n_uy",
                "l10n_ve",
                "l10n_vn",
                "lunch",
                #~ "mail",
                "marketing",
                "marketing_campaign",
                "marketing_campaign_crm_demo",
                "membership",
                #~ "mrp",
                "mrp_byproduct",
                "mrp_jit",
                "mrp_operations",
                "mrp_repair",
                "multi_company",
                #~ "note",
                "note_pad",
                "pad",
                "pad_project",
                #~ "plugin",
                "plugin_outlook",
                "plugin_thunderbird",
                "point_of_sale",
                #~ "portal",
                "portal_anonymous",
                "portal_claim",
                "portal_crm",
                "portal_event",
                "portal_hr_employees",
                "portal_project",
                "portal_project_issue",
                "portal_project_long_term",
                "portal_sale",
                "portal_stock",
                #~ "process",
                "procurement",
                #~ "product",
                "product_expiry",
                "product_manufacturer",
                "product_margin",
                "product_visible_discount",
                #~ "project",
                "project_gtd",
                "project_issue",
                "project_issue_sheet",
                "project_long_term",
                "project_mrp",
                "project_timesheet",
                #~ "purchase",
                #~ "purchase_analytic_plans",#Error to fix
                "purchase_double_validation",
                "purchase_requisition",
                #"report_intrastat",
                "report_webkit",
                "resource",
                #~ "sale",
                #"sale_analytic_plans",#Error to fix
                "sale_crm",
                "sale_journal",
                "sale_margin",
                "sale_mrp",
                "sale_order_dates",
                "sale_stock",
                "share",
                #~ "stock",
                "stock_invoice_directly",
                #"stock_location",#Error to fix
                "stock_no_autopicking",
                "subscription",
                "survey",
                "warning",
                "web_analytics",
                "web_linkedin",
                "web_shortcuts",
                #End list of all oficial modules
                "oml",
                ],
    "author" : "Vauxoo",
    "description" : """
Install all apps needed to comply with Mexican laws plus all oficial modules 
===================================================

This module will install for you:
  
  -  oml module
  
  - And all oficial modules (account, stock, mrp, purchase, sale...)
                    """,
    "website" : "http://www.vauxoo.com",
    "category" : "Localization/Application",
    "init_xml" : [],
    "demo_xml" : [],
    "update_xml" : [],
    "test" : [],
    "images" : [],
    "auto_install": False,
    "application": True,
    "installable": True,
}
