name: pre-commit

on:
  pull_request:
    branches:
      - "15.0*"
  push:
    branches:
      - "15.0"

jobs:
  pre-commit-vauxoo:
    runs-on: ubuntu-latest
    name: pre-commit-vauxoo
    steps:
      - uses: actions/checkout@v2
      - name: Cache pre-commit and pip packages
        id: cache-pre-commit-pip
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pre-commit
            ~/.cache/pip
          key: cache-pre-commit-pip
      - name: Install pre-commit-vauxoo
        run: pip install --upgrade pre-commit-vauxoo
      - name: Run pre-commit-vauxoo
        run: pre-commit-vauxoo
