name: tests

on:
  pull_request_target:
    branches:
      - "15.0"
  push:
    branches:
      - "15.0"

env:
  CI_COMMIT_SHA: ${{ github.event.pull_request.head.sha || github.sha }}
  CI_PROJECT_NAMESPACE: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
  CI_PROJECT_NAME: ${{ github.event.pull_request.head.repo.name || github.event.repository.name }}

jobs:
  pre-commit-vauxoo:
    runs-on: ubuntu-latest
    name: pre-commit-vauxoo
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.CI_COMMIT_SHA }}
      - name: Cache pre-commit and pip packages
        id: cache-pre-commit-pip
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pre-commit
            ~/.cache/pip
          key: cache-pre-commit-pip
      - name: Install pre-commit-vauxoo
        run: pip install --upgrade pre-commit-vauxoo
      - name: Run pre-commit-vauxoo
        run: pre-commit-vauxoo
  no-dependency-files:
    runs-on: ubuntu-latest
    name: No dependency files
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.CI_COMMIT_SHA }}
      - name: Ensure dependency files don't exist
        run: |
          for reqfile in requirements.txt oca_dependencies.txt ; do
              if [ -f ${reqfile} ] ; then
                  echo "Please avoid adding requirement files to this repo, because requirements will be installed in all project depending on this one."
                  echo "If you need them for test to work, you can use test-${reqfile} instead of ${reqfile}"
                  exit 1
                fi
           done
  build_docker:
    runs-on: ubuntu-latest
    name: Build Docker and test Odoo
    env:
      SSH_AUTH_SOCK: /tmp/ssh_agent.sock
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.CI_COMMIT_SHA }}
          persist-credentials: false
      - name: Cache pip packages
        id: cache-pip-build
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: cache-pip-build
      - name: Set ssh keys
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.PRIVATE_DEPLOY_KEY }}"
          mkdir -p ~/.ssh/
          ssh-keyscan -H git.vauxoo.com >> ~/.ssh/known_hosts
      - name: Install dependencies
        run: |
          pip install -U deployv vxci
          sudo apt update
          sudo apt install dos2unix
      - name: Build image
        env:
          PRIVATE_DEPLOY_KEY: ${{ secrets.PRIVATE_DEPLOY_KEY }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          ORCHEST_REGISTRY: ${{ secrets.ORCHEST_REGISTRY }}
          ORCHEST_TOKEN: ${{ secrets.ORCHEST_TOKEN }}
        run: |
          source variables.sh
          vxci check_keys
          vxci build_image --push_image
      - name: Test odoo image
        run: |
          source variables.sh
          slugified_branch=$(python -c "from vxci.common import slugify; print(slugify('${GITHUB_HEAD_REF:-${GITHUB_REF_NAME}}'))")
          source ${slugified_branch}/image_name.env
          vxci test_repo --allow_deprecated
